[[pages]]
path = "tool_pages/main_page.py"
name = "首页"
icon = "🏠"

[[pages]]
path = "tool_pages/location_display.py"
name = "仓库位置信息"
icon = "📍"

[[pages]]
path = "tool_pages/location_set.py"
name = "仓库位置信息设置(数据库)"
icon = "🛠️"

[[pages]]
path = "tool_pages/device_management.py"
name = "设备状态管理"
icon = "🦾"

[[pages]]
path = "tool_pages/car_position_calibration.py"
name = "穿梭车位置校准"
icon = "⚙️"

[[pages]]
path = "tool_pages/task_auto_advanced.py"
name = "beta - 高级操作(数据库)"
icon = "🎩"

[[pages]]
path = "tool_pages/task_auto_base.py"
name = "beta - 基础操作"
icon = "🚦"  

[[pages]]
path = "tool_pages/car_move.py"
name = "单步 - 穿梭车移动操作"
icon = "🚗" 

[[pages]]
path = "tool_pages/good_move.py"
name = "单步 - 货物移动操作"
icon = "📦" 

[[pages]]
path = "tool_pages/task_outband_by_step.py"
name = "单步 - 出库操作"
icon = "⬆️"

[[pages]]
path = "tool_pages/task_inband_by_step.py"
name = "单步 - 入库操作"
icon = "⬇️" 

[[pages]]
path = "tool_pages/car_cross_layer_by_step.py"
name = "单步 - 穿梭车跨层操作"
icon = "🚚" 

[[pages]]
path = "tool_pages/location_update.py"
name = "仓库位置信息更新(数据库)"
icon = "♻️"